// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetCodeforcesProblem implements get-codeforces-problem operation.
//
// Get Codeforces Problem.
//
// GET /codeforces/problems/{contest_id}/{index}
func (UnimplementedHandler) GetCodeforcesProblem(ctx context.Context, params GetCodeforcesProblemParams) (r *CodeforcesProblem, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
