// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetCodeforcesProblemParams is parameters of get-codeforces-problem operation.
type GetCodeforcesProblemParams struct {
	// Contest ID.
	ContestID int
	// Problem Index. Usually, a letter or letter with digit(s) indicating the problem index in a contest.
	Index string
}

func unpackGetCodeforcesProblemParams(packed middleware.Parameters) (params GetCodeforcesProblemParams) {
	{
		key := middleware.ParameterKey{
			Name: "contest_id",
			In:   "path",
		}
		params.ContestID = packed[key].(int)
	}
	{
		key := middleware.ParameterKey{
			Name: "index",
			In:   "path",
		}
		params.Index = packed[key].(string)
	}
	return params
}

func decodeGetCodeforcesProblemParams(args [2]string, argsEscaped bool, r *http.Request) (params GetCodeforcesProblemParams, _ error) {
	// Decode path: contest_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "contest_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ContestID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "contest_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: index.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "index",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Index = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "index",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
